---
- name: Check if "{{ ssh_pub_key }}" file exists in master node.
  ansible.builtin.stat:
    path: "{{ ssh_pub_key }}"
  register: public_key
  delegate_to: "{{ groups.master_node[0] }}"

- name: Create local .ssh directory.
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: 0700
  delegate_to: "{{ groups.master_node[0] }}"
  become: true
  become_user: "{{ usr_name }}"

- name: Change "{{ ssh_dir }}" mode (used to access to the private key).
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: 0777
  delegate_to: "{{ groups.master_node[0] }}"
  become: true
  become_user: "{{ usr_name }}"

- name: Define ed25519 ssh keys on master node if it does not exists.
  community.crypto.openssh_keypair:
    path: "{{ ssh_priv_key }}"
    type: ed25519
  run_once: True
  delegate_to: "{{ groups.master_node[0] }}"
  when: public_key.stat.exists == false
  become: true
  become_user: "{{ usr_name }}"
